-- Active: 1721571957405@@localhost@3306
CREATE DATABASE todoAppDB;

USE todoAppDB;

CREATE TABLE tasks (id BINARY PRIMARY KEY NOT NULL, task VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL DEFAULT(FALSE))